# Generated by Django 4.2.13 on 2024-07-02 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usersapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('profilepic', models.ImageField(null=True, upload_to='profile_media/')),
                ('phoneno', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('users', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usersapp.users')),
            ],
        ),
    ]
