# Generated by Django 4.2.13 on 2024-07-02 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0002_profileskills_profileeducation_profilecertification'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='certificate',
            field=models.ManyToManyField(related_name='certification', to='profileapp.profilecertification'),
        ),
        migrations.AddField(
            model_name='profile',
            name='education',
            field=models.ManyToManyField(related_name='education', to='profileapp.profileeducation'),
        ),
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=models.ManyToManyField(related_name='Profile', to='profileapp.profileskills'),
        ),
    ]
