# Generated by Django 4.2.13 on 2024-07-03 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0004_profileexperience'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='experience',
            field=models.ManyToManyField(related_name='experience', to='profileapp.profileexperience'),
        ),
    ]
